# Project Information
site_name: PagerDuty Operational Reviews Documentation
site_description: A collection of information about PagerDuty customers run regular operational reviews with metrics. Not only how to run operational review meetings, but how to prepare, who to invite, and how to make them actionable.
site_author: PagerDuty, Inc.
site_url: https://reviews.pagerduty.com/

# Repository
repo_url: https://github.com/pagerduty/operational-review-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme:
  name: pagerduty
  title: 'Operational Reviews'

# Contents
nav:
  - Home: 'index.md'
  - Introduction: 'introduction.md'
  - The Reviews:
    - On-Call Review: 'reviews/oncall.md'
    - Service Review: 'reviews/service.md'
    - Business Review: 'reviews/business.md'
  - Definitions: 'definitions.md'
  - Next Steps: 'next_steps.md'
  - Additional Resources: 'resources.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:

# Development URL, bind to local only.
dev_addr: '127.0.0.1:8000'
